age = int(input("enter the value of age "))
name = str(input("enter user's name "))
no_of_kids = int(input("enter the value of the number of kids "))
date_of_birth = 2024 - int(age)
print("Hello " + name + ", you are " + str(age) + " years of age and you've had " + str(no_of_kids) + " kids in the past few years, you were born in the year " + str(date_of_birth))