"""
1) Variable Data Types 
a) Create a variable called "Date_Of_Birth" and assign it the year you were born (or any random 
year) using the right datatype. Print the value of the variable. 
b) What is the difference between an integer and a floating-point number in Python? Backup your 
explanation with an example for each.
"""
"""Date_of_Birth =int(input("enter year of birth "))
print(Date_of_Birth)
"""
#the difference is that floating point number is a negative or positive value containing one or more decimals. while an integer is a whole number.


"""

2) Basic Operations 
a) Write a Python program that adds two numbers together and prints the result. 
b) Write a Python program that takes a number as input and multiplies it by 10. Print the result.
"""
"""value_1 = int(input("enter the first value "))
value_2 = int(input("enter the second value "))
answer = value_1 + value_2
print(answer)


a = int(input("enter any preferred number "))
result = int(a) * 10
print(result)
"""


"""
3) Control Structures 
a) Write a Python program that checks if a number is even or odd. If the number is even, print 
"Even", otherwise print "Odd". 
b) Write a Python program that takes a number as input and checks if it is positive, negative, or 
zero. Print the result.
"""



"""
4) Lists and Loops 
a) Create a list of numbers from 1 to 10. Print each number in the list using a loop. 
b) Write a Python program that takes a list of numbers as input and returns the sum of all the 
numbers in the list.
c) Create a dictionary ‘colleague_name’ storing all your colleague names. Hint: Use sequence of 
numbers as their key. 

5) Functions 
a) Write a Python function that takes three numbers as input and return their multiplication.
b) Write a Python function that takes a list of numbers as input and returns the average of all the 
numbers in the list.6) Libraries and Modules 

6. 
Ask for the person's age (age) and the amount they can save monthly (savings).

If age > 50, print "You should be focusing on retirement savings".
Then, if savings >= 10000, print "You are on track for a comfortable retirement".-
Otherwise, print "Consider increasing your savings for a secure retirement".
If age <= 50, print "You have time to plan your savings".
Then, if savings >= 5000, print "You are saving well for your future".
Otherwise, print "Try to increase your savings to secure your future".
"""
age = int(input("enter the value for age "))
savings = int(input("enter the value for savings "))
if age >= 50:
    print("you should be focusing on retirement savings")
elif savings >= 10000 :
    print("You are on track for a comfortable retirement")
else:
    print("Consider increasing your savings for a secure retirement")


if age <= 50:
    print("You have time to plan your savings")
elif savings <= 5000:
    print("You are saving well for your future")
else:
    print("Try to increase your saving to secure your future")



"""
7) Explain the following terms relating to Python programming Language with examples where needed
a) Escape Sequence
b) Keywords
c) Datatypes
d) Dictionary 
e) Interpreter
"""
# escape sequence: is used to insert illegal characters in a string. a backslash is used followed by characters you want to insert e.g \n, \t, \\.
# keywords:are reserved words that cannot be used as variables, function names or any other identifiers e.g None, True, False, assert, assync, and, return, pass etc.
# datatypes:Python is an object oriented language, everything in it has an object. Each object isna specific type and a class defines each type - THIA IA THE Definition of data type. e.g numeric data types, text data type, booleans.
# dictionary: helps to section values in key: value pairs. e.g: class_log = [boys: 12, girls: 6, teachers : 2]
#interpreter: is a computer program that converts high level program to a machine code. it translates your code to something the computer can understand.



"""
8) Give a brief history of python, who built it, what led to Python and others, state the current version 
of python you are using."""
#Python was created in the year 1991. a group of researchers led by Guido Van Rossum brought about the existence of Python programming language.
#The current version Im using is version 3.12.4.


"""
9) Mentions some tools used the career listed below, write extensively on the career you are choosing 
after this course. Explain what the career entails and the problem skilled professionals in the career
solve in the real-world market.
a) Data Scientist
b) Software Engineer
c) Data Engineer
d) Data Analytics
e) Web Developer (Backend Developer)
f) Machine Learning Engineer
"""
# Data Analytics: is the process of systematically applying statistical and/or logical techniques to describe and illustrate, condense and recap, and evaluate data.



"""
10) Give a feedback on this Python course, your instructor and this examination.
"""
#The Python programming language is an open source programming language that can be incorporated into muliple fiekds like machine learning and AI.
#It is versaile and deemed the easiest programming language that lives true ti its title.
#The course was smooth and easy to grasp if ones mind is put into proper learning.
#The tutor is patient and manages to carry all student along. He teaches step by step how to create and push readable codes and his teachings are reliable.
#Thia examination is challenging and questions your skill in said field of study.



"""
#answer any 7 questions, 1,2,3,6 and 10 are compulsory
"""

